In [1]:
import pandas as pd

# Mock Data: A small server log
data = {
    'Level': ['INFO', 'ERROR', 'DEBUG', 'ERROR', 'INFO'],
    'Message': ['System Start', 'Database Timeout', 'Checking Port', 'Auth Failure', 'User Login'],
    'Latency': [10.5, 450.2, 5.1, 89.0, 12.3]
}

# We set the index to specific 'Log_IDs' to practice .loc
df = pd.DataFrame(data, index=['L101', 'L102', 'L103', 'L104', 'L105'])

# Display to verify
print(df)

      Level           Message  Latency
L101   INFO      System Start     10.5
L102  ERROR  Database Timeout    450.2
L103  DEBUG     Checking Port      5.1
L104  ERROR      Auth Failure     89.0
L105   INFO        User Login     12.3

Problem Set 1: The Navigator (loc & iloc)
Goal: Retrieve specific evidence from the logs without crashing the system.

1. The Target: Use .loc to find the Message for the log ID 'L104'.

2. The Scan: Use .iloc to get the last two rows of the entire DataFrame.

3. The Specifics: Use .iloc to find the Latency (which is column index 2) of the first row.

4. The Filter: (Advanced) Use .loc to find all rows where the Level is 'ERROR'.

Hint: df.loc[df['Level'] == 'ERROR']

In [13]:
#The Target: Use .loc to find the Message for the log ID 'L104'.
df.loc['L104']['Message']

'Auth Failure'

In [19]:
#The Scan: Use .iloc to get the last two rows of the entire DataFrame.
df.iloc[-2:]

      Level       Message  Latency
L104  ERROR  Auth Failure     89.0
L105   INFO    User Login     12.3

In [22]:
# The Specifics: Use .iloc to find the Latency (which is column index 2) of the first row.
df.iloc[1]['Latency']

np.float64(450.2)

In [25]:
# The Filter: (Advanced) Use .loc to find all rows where the Level is 'ERROR'.
df.loc[df['Level'] == 'ERROR']

      Level           Message  Latency
L102  ERROR  Database Timeout    450.2
L104  ERROR      Auth Failure     89.0

In [1]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

# Building the chain: A -> B -> C
head = Node("User_Alpha")
node_b = Node("User_Beta")
node_c = Node("User_Gamma")

head.next = node_b
node_b.next = node_c

NameError: name 'data' is not defined